language: ruby
rvm: "2.3"

## Get our environment a little better.
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 jq curl python3-yaml
## Possible other way.
install:
  - gem install kwalify
script:
  ## Quick user data check.
  - kwalify -E -m .testing/datasets.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
  - kwalify -E -f ./.testing/datasets.schema.yaml gaf.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
  ## Get tools and files.
  - wget http://current.geneontology.org/bin/owltools && chmod 755 owltools
  - wget http://current.geneontology.org/ontology/extensions/go-gaf.owl
  - ruby ./.testing/runner.rb

notifications:
  email:
    - sjcarbon@lbl.gov
    # - cjmungall@lbl.gov
