language: ruby
rvm: "1.9.3"

# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq kwalify
## Possible other way.
install:
  - gem install kwalify
script:
  ## Quick user data check.
  - kwalify -E -m .testing/datasets.schema.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
  - kwalify -E -f ./.testing/datasets.schema.yaml gaf.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
notifications:
  email:
    - sjcarbon@lbl.gov
    # - cjmungall@lbl.gov
